/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViviendaRouteImport } from './routes/vivienda'
import { Route as RociadoRouteImport } from './routes/rociado'
import { Route as NebulizacionRouteImport } from './routes/nebulizacion'
import { Route as LecturasRouteImport } from './routes/lecturas'
import { Route as IntraRouteImport } from './routes/intra'
import { Route as EntomologiaRouteImport } from './routes/entomologia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncViviendaRouteImport } from './routes/api/public/sync-vivienda'
import { Route as ApiPublicSyncRociadoRouteImport } from './routes/api/public/sync-rociado'
import { Route as ApiPublicSyncLecturasRouteImport } from './routes/api/public/sync-lecturas'
import { Route as ApiPublicSyncLarvarioRouteImport } from './routes/api/public/sync-larvario'
import { Route as ApiPublicSyncIntraRouteImport } from './routes/api/public/sync-intra'
import { Route as ApiPublicSyncEntomologiaRouteImport } from './routes/api/public/sync-entomologia'

const ViviendaRoute = ViviendaRouteImport.update({
  id: '/vivienda',
  path: '/vivienda',
  getParentRoute: () => rootRouteImport,
} as any)
const RociadoRoute = RociadoRouteImport.update({
  id: '/rociado',
  path: '/rociado',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulizacionRoute = NebulizacionRouteImport.update({
  id: '/nebulizacion',
  path: '/nebulizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturasRoute = LecturasRouteImport.update({
  id: '/lecturas',
  path: '/lecturas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntraRoute = IntraRouteImport.update({
  id: '/intra',
  path: '/intra',
  getParentRoute: () => rootRouteImport,
} as any)
const EntomologiaRoute = EntomologiaRouteImport.update({
  id: '/entomologia',
  path: '/entomologia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncViviendaRoute = ApiPublicSyncViviendaRouteImport.update({
  id: '/api/public/sync-vivienda',
  path: '/api/public/sync-vivienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncRociadoRoute = ApiPublicSyncRociadoRouteImport.update({
  id: '/api/public/sync-rociado',
  path: '/api/public/sync-rociado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncLecturasRoute = ApiPublicSyncLecturasRouteImport.update({
  id: '/api/public/sync-lecturas',
  path: '/api/public/sync-lecturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncLarvarioRoute = ApiPublicSyncLarvarioRouteImport.update({
  id: '/api/public/sync-larvario',
  path: '/api/public/sync-larvario',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncIntraRoute = ApiPublicSyncIntraRouteImport.update({
  id: '/api/public/sync-intra',
  path: '/api/public/sync-intra',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncEntomologiaRoute =
  ApiPublicSyncEntomologiaRouteImport.update({
    id: '/api/public/sync-entomologia',
    path: '/api/public/sync-entomologia',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/intra': typeof IntraRoute
  '/lecturas': typeof LecturasRoute
  '/nebulizacion': typeof NebulizacionRoute
  '/rociado': typeof RociadoRoute
  '/vivienda': typeof ViviendaRoute
  '/api/public/sync-entomologia': typeof ApiPublicSyncEntomologiaRoute
  '/api/public/sync-intra': typeof ApiPublicSyncIntraRoute
  '/api/public/sync-larvario': typeof ApiPublicSyncLarvarioRoute
  '/api/public/sync-lecturas': typeof ApiPublicSyncLecturasRoute
  '/api/public/sync-rociado': typeof ApiPublicSyncRociadoRoute
  '/api/public/sync-vivienda': typeof ApiPublicSyncViviendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/intra': typeof IntraRoute
  '/lecturas': typeof LecturasRoute
  '/nebulizacion': typeof NebulizacionRoute
  '/rociado': typeof RociadoRoute
  '/vivienda': typeof ViviendaRoute
  '/api/public/sync-entomologia': typeof ApiPublicSyncEntomologiaRoute
  '/api/public/sync-intra': typeof ApiPublicSyncIntraRoute
  '/api/public/sync-larvario': typeof ApiPublicSyncLarvarioRoute
  '/api/public/sync-lecturas': typeof ApiPublicSyncLecturasRoute
  '/api/public/sync-rociado': typeof ApiPublicSyncRociadoRoute
  '/api/public/sync-vivienda': typeof ApiPublicSyncViviendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/intra': typeof IntraRoute
  '/lecturas': typeof LecturasRoute
  '/nebulizacion': typeof NebulizacionRoute
  '/rociado': typeof RociadoRoute
  '/vivienda': typeof ViviendaRoute
  '/api/public/sync-entomologia': typeof ApiPublicSyncEntomologiaRoute
  '/api/public/sync-intra': typeof ApiPublicSyncIntraRoute
  '/api/public/sync-larvario': typeof ApiPublicSyncLarvarioRoute
  '/api/public/sync-lecturas': typeof ApiPublicSyncLecturasRoute
  '/api/public/sync-rociado': typeof ApiPublicSyncRociadoRoute
  '/api/public/sync-vivienda': typeof ApiPublicSyncViviendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entomologia'
    | '/intra'
    | '/lecturas'
    | '/nebulizacion'
    | '/rociado'
    | '/vivienda'
    | '/api/public/sync-entomologia'
    | '/api/public/sync-intra'
    | '/api/public/sync-larvario'
    | '/api/public/sync-lecturas'
    | '/api/public/sync-rociado'
    | '/api/public/sync-vivienda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entomologia'
    | '/intra'
    | '/lecturas'
    | '/nebulizacion'
    | '/rociado'
    | '/vivienda'
    | '/api/public/sync-entomologia'
    | '/api/public/sync-intra'
    | '/api/public/sync-larvario'
    | '/api/public/sync-lecturas'
    | '/api/public/sync-rociado'
    | '/api/public/sync-vivienda'
  id:
    | '__root__'
    | '/'
    | '/entomologia'
    | '/intra'
    | '/lecturas'
    | '/nebulizacion'
    | '/rociado'
    | '/vivienda'
    | '/api/public/sync-entomologia'
    | '/api/public/sync-intra'
    | '/api/public/sync-larvario'
    | '/api/public/sync-lecturas'
    | '/api/public/sync-rociado'
    | '/api/public/sync-vivienda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntomologiaRoute: typeof EntomologiaRoute
  IntraRoute: typeof IntraRoute
  LecturasRoute: typeof LecturasRoute
  NebulizacionRoute: typeof NebulizacionRoute
  RociadoRoute: typeof RociadoRoute
  ViviendaRoute: typeof ViviendaRoute
  ApiPublicSyncEntomologiaRoute: typeof ApiPublicSyncEntomologiaRoute
  ApiPublicSyncIntraRoute: typeof ApiPublicSyncIntraRoute
  ApiPublicSyncLarvarioRoute: typeof ApiPublicSyncLarvarioRoute
  ApiPublicSyncLecturasRoute: typeof ApiPublicSyncLecturasRoute
  ApiPublicSyncRociadoRoute: typeof ApiPublicSyncRociadoRoute
  ApiPublicSyncViviendaRoute: typeof ApiPublicSyncViviendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vivienda': {
      id: '/vivienda'
      path: '/vivienda'
      fullPath: '/vivienda'
      preLoaderRoute: typeof ViviendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rociado': {
      id: '/rociado'
      path: '/rociado'
      fullPath: '/rociado'
      preLoaderRoute: typeof RociadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebulizacion': {
      id: '/nebulizacion'
      path: '/nebulizacion'
      fullPath: '/nebulizacion'
      preLoaderRoute: typeof NebulizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturas': {
      id: '/lecturas'
      path: '/lecturas'
      fullPath: '/lecturas'
      preLoaderRoute: typeof LecturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intra': {
      id: '/intra'
      path: '/intra'
      fullPath: '/intra'
      preLoaderRoute: typeof IntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entomologia': {
      id: '/entomologia'
      path: '/entomologia'
      fullPath: '/entomologia'
      preLoaderRoute: typeof EntomologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-vivienda': {
      id: '/api/public/sync-vivienda'
      path: '/api/public/sync-vivienda'
      fullPath: '/api/public/sync-vivienda'
      preLoaderRoute: typeof ApiPublicSyncViviendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-rociado': {
      id: '/api/public/sync-rociado'
      path: '/api/public/sync-rociado'
      fullPath: '/api/public/sync-rociado'
      preLoaderRoute: typeof ApiPublicSyncRociadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-lecturas': {
      id: '/api/public/sync-lecturas'
      path: '/api/public/sync-lecturas'
      fullPath: '/api/public/sync-lecturas'
      preLoaderRoute: typeof ApiPublicSyncLecturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-larvario': {
      id: '/api/public/sync-larvario'
      path: '/api/public/sync-larvario'
      fullPath: '/api/public/sync-larvario'
      preLoaderRoute: typeof ApiPublicSyncLarvarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-intra': {
      id: '/api/public/sync-intra'
      path: '/api/public/sync-intra'
      fullPath: '/api/public/sync-intra'
      preLoaderRoute: typeof ApiPublicSyncIntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-entomologia': {
      id: '/api/public/sync-entomologia'
      path: '/api/public/sync-entomologia'
      fullPath: '/api/public/sync-entomologia'
      preLoaderRoute: typeof ApiPublicSyncEntomologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntomologiaRoute: EntomologiaRoute,
  IntraRoute: IntraRoute,
  LecturasRoute: LecturasRoute,
  NebulizacionRoute: NebulizacionRoute,
  RociadoRoute: RociadoRoute,
  ViviendaRoute: ViviendaRoute,
  ApiPublicSyncEntomologiaRoute: ApiPublicSyncEntomologiaRoute,
  ApiPublicSyncIntraRoute: ApiPublicSyncIntraRoute,
  ApiPublicSyncLarvarioRoute: ApiPublicSyncLarvarioRoute,
  ApiPublicSyncLecturasRoute: ApiPublicSyncLecturasRoute,
  ApiPublicSyncRociadoRoute: ApiPublicSyncRociadoRoute,
  ApiPublicSyncViviendaRoute: ApiPublicSyncViviendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
