/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViviendaRouteImport } from './routes/vivienda'
import { Route as LecturasRouteImport } from './routes/lecturas'
import { Route as EntomologiaRouteImport } from './routes/entomologia'
import { Route as IndexRouteImport } from './routes/index'

const ViviendaRoute = ViviendaRouteImport.update({
  id: '/vivienda',
  path: '/vivienda',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturasRoute = LecturasRouteImport.update({
  id: '/lecturas',
  path: '/lecturas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntomologiaRoute = EntomologiaRouteImport.update({
  id: '/entomologia',
  path: '/entomologia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/lecturas': typeof LecturasRoute
  '/vivienda': typeof ViviendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/lecturas': typeof LecturasRoute
  '/vivienda': typeof ViviendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entomologia': typeof EntomologiaRoute
  '/lecturas': typeof LecturasRoute
  '/vivienda': typeof ViviendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entomologia' | '/lecturas' | '/vivienda'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entomologia' | '/lecturas' | '/vivienda'
  id: '__root__' | '/' | '/entomologia' | '/lecturas' | '/vivienda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntomologiaRoute: typeof EntomologiaRoute
  LecturasRoute: typeof LecturasRoute
  ViviendaRoute: typeof ViviendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vivienda': {
      id: '/vivienda'
      path: '/vivienda'
      fullPath: '/vivienda'
      preLoaderRoute: typeof ViviendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturas': {
      id: '/lecturas'
      path: '/lecturas'
      fullPath: '/lecturas'
      preLoaderRoute: typeof LecturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entomologia': {
      id: '/entomologia'
      path: '/entomologia'
      fullPath: '/entomologia'
      preLoaderRoute: typeof EntomologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntomologiaRoute: EntomologiaRoute,
  LecturasRoute: LecturasRoute,
  ViviendaRoute: ViviendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
